### PR TITLE
Catkinized enu

### PR DESCRIPTION
**Pull request by chadrockey**
It's probably best to merge this into new groovy-devel and hydro-devel branches.  Otherwise it's going to destroy your current workspaces.

### CODE REVIEW

**Comment by abencz** [comment]
Very cool!

Thank you for contributing this back :)

**Comment by abencz** [comment]
I'm just going to merge this into master - repo has a fuerte branch that can be used to maintain a rosbuild variant.

**Comment by mikepurvis** [comment]
Probably best as part of this that we include the package name in the executables, eg, to_fix becomes enu_to_fix, from_fix becomes enu_from_fix.

**Comment by mikepurvis** [comment]
Okay, changed the executables as of 33ec0e267aca143738c92fc341f829ac99f4db67.

**Pull request merged**
