### PR TITLE
Covariance and Frame_id Fixes

### PR DESCRIPTION
**Pull request by chadrockey**
This pull request does two things:

1) Sets covariance to -1.  The ROS convention is to have -1 for an invalid covariance.  This might break robot_pose_ekf because it handles covariance incorrectly.  Setting covariance to a large number means that measurement is valid, but not sure.

2) Allows a configurable frame_id.  The GPS global frame_id needs to be injected in this node, while the child_frame_id and NavSatFix is the frame_id of the antenna, which needs to be a child of base_link.

I'm not 100% sure of your backward compatible use cases, so let me know and I'll make sure this won't break anything for you.  For instance, if you need odom.header.frame_id === odom.child_frame_id === navsatfix.header.frame_id, we could default the 'output_frame_id' to be the empty string, and know that's a special case.

### CODE REVIEW

**Comment by mikepurvis** [comment]
Hi Chad, thanks—the frame_id parameterization is appreciated! Regarding the matter of the covariance, I'd prefer to see this stay usable as the glue between nmea_gps_driver and robot_pose_ekf. Is there a way that we can make the correct behaviour the default, but provide an option for compatibility with the currently-used robot_pose_ekf?

**Comment by chadrockey** [comment]
@mikepurvis I'm not 100% it will break it, but I'm not familiar with the gps changes inside of robot_pose_ekf.

We could always just set an 'invalid_covariance_value' parameter, defaults to -1.0 and robot_pose_ekf users can set it to 1e6 or some other large number.

**Comment by chadrockey** [comment]
@mikepurvis  I added the change I suggested in https://github.com/chadrockey/enu/commit/5f91f2ec8a9af8e4c1f669996797a702d7b6a12d

For most ROS cases, this should be expected.  for robot_pose_ekf, it should be set back to 1e6.

**Comment by mikepurvis** [comment]
Okay, awesome. LGTM.

I did the merge, but I just realised I don't have push rights on this repo for some reason. @abencz, please merge when you get a chance.

**Pull request merged**
